// All player-visible strings live here — switching language is a data change, not a code change.
export const STR = {
  title: "NEON ARENA",
  tagline: "Free-for-all neon deathmatch",
  enterName: "CALLSIGN",
  play: "ENTER ARENA",
  connecting: "CONNECTING…",
  reconnecting: "CONNECTION LOST — RECONNECTING…",
  waiting: "Waiting for the arena…",
  clickToPlay: "CLICK TO LOCK MOUSE & FIGHT",
  paused: "PAUSED — CLICK TO RESUME",
  health: "ARMOR",
  score: "FRAGS",
  scoreboard: "SCOREBOARD",
  you: "YOU",
  respawnIn: "RESPAWN IN",
  fragged: "FRAGGED",
  fraggedBy: "Fragged by",
  fragged_you: "You fragged",
  leader: "LEADER",
  invite: "Share this link to invite fighters:",
  copy: "COPY LINK",
  copied: "COPIED!",
  controlsTitle: "CONTROLS",
  ctrlMove: "Move",
  ctrlLook: "Look / Aim",
  ctrlFire: "Fire",
  ctrlJump: "Jump",
  ctrlScore: "Scoreboard",
  ctrlKbd: "WASD",
  ctrlMouse: "Mouse",
  ctrlFireKey: "Left-click / hold",
  ctrlJumpKey: "Space",
  ctrlScoreKey: "Tab",
  mobileHint: "Left side: move • Right side: aim • buttons: fire / jump",
  defaultName: "Recruit",
};
